name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    env:
      MONGO_URL: mongodb://localhost:27017/tododb

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      ###########################
      # Backend
      ###########################

      - name: Install backend dependencies
        working-directory: ./todo-backend
        run: npm install

      - name: Run backend tests
        working-directory: ./todo-backend
        run: npm test

      ###########################
      # Frontend
      ###########################

      - name: Install frontend dependencies
        working-directory: ./todo-frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./todo-frontend
        run: npm test

      - name: Build frontend
        working-directory: ./todo-frontend
        run: npm run build

      ###########################
      # Docker Build (optional)
      ###########################

      - name: Docker Build Backend
        run: docker build -t backend ./todo-backend

      - name: Docker Build Frontend
        run: docker build -t frontend ./todo-frontend
