name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Backend
      - name: Install backend dependencies
        working-directory: ./todo-backend
        run: npm install

      - name: Lint or test backend (optional)
        working-directory: ./todo-backend
        run: echo "no backend test yet"  # remplacer par "npm test" si tu en as

      # Frontend
      - name: Install frontend dependencies
        working-directory: ./todo-frontend
        run: npm install

      - name: Build frontend
        working-directory: ./todo-frontend
        run: npm run build

      # Docker builds
      - name: Docker Build Backend
        run: docker build -t backend ./todo-backend

      - name: Docker Build Frontend
        run: docker build -t frontend ./todo-frontend
